#!/bin/bash

# get image from fterm
# image=$(./endorse_fterm image)

# image=/storage/liberec3-tul/home/pavel_exner/workspace/flow123d_images/flow123d_geomop-gnu:2.0.0.sif
# image=/storage/liberec3-tul/home/pavel_exner/workspace/flow123d_images/endorse.sif
# image=/home/paulie/Workspace/Endorse-2Dtest-Bayes/flow123d_geomop-gnu:2.0.0.sif
image=/home/paulie/Workspace/Endorse-2Dtest-Bayes/endorse.sif
echo $image
